server:
  port: 8080

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health, gateway, prometheus

integration:
  rate-limiter:
    service:
      url: http://localhost:8081

spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true